### PR TITLE
Update ratatui to 0.28

### PR DESCRIPTION
**Pull request by tomgroenwoldt**
Hi, I'm currently in the process of using your crate and so far it worked out quite nice for my use case. The only problem I faced was conflicting `ratatui` versions.

This PR updates `ratatui` to `0.28` and adjusts the (now) deprecated functions.

### CODE REVIEW

**Comment by gin66** [comment]
Thanks for the patch.

**Comment by sgrimee** [comment]
Thank you, I was waiting for this!
Small suggestion to update to 0.12.0, not just 0.11.3 as it is a breaking change.
Cheers!

**Comment by gin66** [comment]
Strange. The patch has not shown up in master. Perhaps I have pressed the wrong button. Anyway, I have then manually updated master to that commit and bumped the version to 0.12.0.

The [semver check](https://github.com/gin66/tui-logger/actions/workflows/semver_checks.yml) has not flagged a problem with 0.11.3. Wonder, if/how that works

**Comment by sgrimee** [comment]
My reasoning was that upgrading ratatui will cause multiple versions of ratatui for apps that use tui-logger, often causing conflicts.
As it is a 0.x release, this comment from the book applies:
"This compatibility convention is different from SemVer in the way it treats versions before 1.0.0. While SemVer says there is no compatibility before 1.0.0, Cargo considers 0.x.y to be compatible with 0.x.z, where y ≥ z and x > 0.
"

**Pull request closed without merging**
